name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 19
            - uses: pnpm/action-setup@v2
            - run: pnpm install
            - run: pnpm run build
            - uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ./dist/
